import { Inter } from "next/font/google";
import "./globals.css";
import AsideBar from "./components/AsideBar/AsideBar";
import HeaderBar from "./components/HeaderBar/HeaderBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EPic sound",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="w-[100vw] max-h-[100vh] flex justify-center items-center bg-[#a8787e] overflow-hidden">
          <div className="flex h-screen backdrop-blur-[9px] backdrop-saturate-[200%] bg-[rgba(23,22,36,0.88)] -webkit-backdrop-filter: blur(9px) saturate(200%)">
            <AsideBar />
            <div className="flex flex-col">
              <HeaderBar />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
