import { Inter } from "next/font/google";
import "./globals.css";
import AsideBar from "./components/AsideBar/AsideBar";
import HeaderBar from "./components/HeaderBar/HeaderBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="w-auto max-h-screen pt-5 pb-5 flex justify-center items-center bg-[#a8787e] overflow-y-hidden">
          <div
            className="grid grid-cols-[100px_auto] m-10  gap-1 grid-rows-[80px_auto]  max-h-screen  backdrop-blur-[9px] backdrop-saturate-[200%] bg-[rgba(23,22,36,0.88)] rounded-[50px] 
      -webkit-backdrop-filter: blur(9px) saturate(200%)"
          >
            <aside id="aside-container" className="w-20 row-span-5">
              <AsideBar />
            </aside>
            <div id="header" className="col-span-4">
              <HeaderBar />
            </div>
            <div className="col-span-4 row-span-4 col-start-2 row-start-2">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
